//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity;
    using System.Globalization;
    using System.Web.Security;

    public partial class Combination
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int CombId { get; set; }
        public string CompanyType { get; set; }
        public string NumberofEmployees { get; set; }
        public string NumberofCustomers { get; set; }
        public string NumberofTransactions { get; set; }
        public Nullable<int> SolutionId { get; set; }
    
        public virtual Solutions Solutions { get; set; }
        public string FullList { get { return CompanyType + " , " + NumberofEmployees + " , " + NumberofCustomers + " , " + NumberofTransactions; } }
    }
}
