//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity;
    using System.Globalization;
    using System.Web.Security;
  
    public partial class Solutions
    {
        public Solutions()
        {
            this.Combination = new HashSet<Combination>();
        }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int SolutionId { get; set; }
        public string HardwareInfrastructure { get; set; }
        public string SoftwareInfrastructure { get; set; }
        public string Software_Applications { get; set; }
        public string Networking { get; set; }
        public string Storage { get; set; }
    
        public virtual ICollection<Combination> Combination { get; set; }
    }
}
